### PR TITLE
Whitelist QOwnNotes website

### PR DESCRIPTION
**Pull request by gwzasmv8**
[QOwnNotes ](https://github.com/pbek/QOwnNotes) is a markdown note app similar to Obsidian but FOSS. The website doesn't contain google trackers or malicious JavaScript code either.

The domain was blocked by 1Hosts (Xtra).

### CODE REVIEW

**Comment by spirillen** [comment]
>  or malicious JavaScript code either.

Well, that's not entirely true... isn't it?

- `https://p.bekerle.com/matomo.js` Matomo tracker
- `https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css` jsdeliver tracing/spying

**Comment by rashedarman** [comment]
> > or malicious JavaScript code either.
> 
> Well, that's not entirely true... isn't it?
> 
>     * `https://p.bekerle.com/matomo.js` Matomo tracker
> 
>     * `https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css` jsdeliver tracing/spying

1. Matomo is a privacy-friendly tracker and ublockorigin (or easyprivacy list) blocks it anyway.
2. How is CDN spying? If you want to hide your IP so bad just use a VPN. Plus it's not even JavaScript that's coming from jsdeliver. What's the point you are trying to make?

Besides, following your logic almost all websites on clearnet, including GitHub and 1Hosts [website](https://o0.pages.dev/) itself has to be blocked as it contains cloudflare analytics, shields cdn, hits counter and such. Please leave the internet. Thank you.

**Comment by spirillen** [comment]
> Matomo is a privacy-friendly tracker and ublockorigin (or easyprivacy list) blocks it anyway.

Can also be very very very very very very privacy invasive, like recording your keystroke, mouse movements etc... read up before commenting, please

> How is CDN spying? If you want to hide your IP so bad just use a VPN. Plus it's not even JavaScript that's coming from jsdeliver. What's the point you are trying to make?

Do you really think that helps you, when they gives a F, for your privacy and they believes it is their right to collect any data about you? It only takes a little script to gather your real browser and IP...

please read up on Privacy, before commenting, been around there for 20+ years

**Comment by rashedarman** [comment]
Either way, do you really think that its a valid reason to block an useful webpage for a FOSS webpage? 1Hosts claims to protect against _ads, trackers, and malware_ and QOwnNotes is none of that. Are we really arguing about something straightforward as that?

**Pull request closed without merging**
